apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: neslihanhemosoftdemo 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: neslihanhemosoftdemo 
    spec:
      containers:
        - name: neslihanhemosoftdemo 
          image: hemosoftdemo.azurecr.io/neslihanhemosoftdemo
          ports:
          - containerPort: 80