apiVersion: v1
kind: Service
metadata:
  name: hemosoftDemo
  labels: 
    app: hemosoftDemo
spec:
  selector:
    app: hemosoftDemo
  ports:
  - name: http
    port: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hemosoftDemo
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hemosoftDemo
  template:
    metadata:
      labels:
        app: hemosoftDemo
        version: v1
    spec:
      containers:
      - name: hemosoftDemo
        image: hemosoftDemo.azurecr.io/hemosoftDemo:#{Build.BuildId}#
        ports:
        - containerPort: 8000 
        env:
        - name: PORT
          value: "8000"